# Generated by Django 4.2.11 on 2024-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_doctor_speciality_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Adreess',
            field=models.CharField(default='Addis Abeba,boyle adebabay geba below', max_length=200),
        ),
    ]
