# Generated by Django 4.2.11 on 2024-04-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_adreess'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='grandname',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
