# Generated by Django 4.2.11 on 2024-04-17 12:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2519876453', max_length=128, region=None),
        ),
    ]
