# Generated by Django 4.2.11 on 2024-04-14 13:33

from django.db import migrations, models
import django.db.models.deletion
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_hospital_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=150)),
                ('pic', models.ImageField(upload_to=patient.models.patientUpload)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
