# Generated by Django 4.2.11 on 2024-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_patientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
