# Generated by Django 4.2.11 on 2024-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='grandname',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
