# Generated by Django 4.2.11 on 2024-04-15 18:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patientrecord_recommandation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
