# Generated by Django 4.2.11 on 2024-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patientrecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
