# Generated by Django 4.2.11 on 2024-04-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_patient_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='img',
            field=models.ImageField(default='defaults/logo.webp', upload_to='hospitals/'),
        ),
    ]
