# Generated by Django 4.2.11 on 2024-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_hospital_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A+', max_length=12),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='type',
            field=models.CharField(choices=[('infectious diseases', 'infectious diseases'), ('deficiency diseases', 'deficiency diseases'), ('hereditary diseases', 'hereditary diseases'), ('physiological diseases', 'physiological diseases'), ('Allergies', 'Allergies'), ('Colds and Flu', 'Colds and Flu'), ('Conjunctivitis', 'Conjunctivitis'), ('Headaches', 'Headaches'), ('Stomach Aches', 'Stomach Aches'), ('Broken Bones', 'Broken Bones')], default='Stomach Aches', max_length=200),
        ),
    ]
